apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      restartPolicy: Always

      # CONTAINERS
      containers:
      - image: prom/prometheus:v2.15.1
        name: prometheus
        args:
        - --storage.tsdb.retention=240h
        - --config.file=/etc/prometheus/prometheus.yml
        # RESSOURCES
        resources:
          requests:
            memory: "128Mi"
            cpu: "49m"
          limits:
            cpu: "1"
            memory: "500Mi"
        # CONTAINER MOUNTS
        volumeMounts:
        - name: cm-prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
          readOnly: true

      # VOLUMES
      volumes:
      - name: cm-prometheus-config
        configMap:
          name: cm-prometheus-config

