apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus-httpsvc-tcp
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP