# demo/grafana kustomization

bases:
- ../../../base/grafana

configMapGenerator:
- name: cm-grafana-config
  files:
    - configs/grafana.ini

- name: cm-grafana-dashboard
  files:
    - configs/dashboard.yaml

- name: cm-grafana-datasource
  files:
    - configs/datasource.yaml

- name: cm-grafana-dashboards
  files:
    - configs/dashboards/vigieinstanceInflux.json
    - configs/dashboards/vigieGoRuntimeLite.json

- name: cm-grafana-dashboards2
  files:
    - configs/dashboards/vigieInfluxQL_fails.json