apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: tls-sec-0

spec:
  minVersion: VersionTLS13
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
  curvePreferences:
    - CurveP521
    - X25519
  preferServerCipherSuites: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: tls-sec-1

spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
  curvePreferences:
    - CurveP521
    - CurveP384
    - X25519
  preferServerCipherSuites: true