apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntwtools
  labels:
    app: ntwtools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntwtools
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ntwtools
    spec:
      restartPolicy: Always

      # CONTAINERS
      containers:
      - name: ntwtools
        image: vincoll/ntwtools:latest

        # RESSOURCES
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "400m"
