{
 "title": "Vigie Instance InfluxDB Fails",
 "tags": [
  "Vigie",
  "InfluxDB"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "TestSuite",
    "label": "testsuite",
    "query": "SHOW TAG VALUES ON vigie WITH KEY = \"testsuite\""
   },
   {
    "name": "TestCase",
    "label": "testcase",
    "query": "SHOW TAG VALUES ON vigie WITH KEY = \"testcase\""
   },
   {
    "name": "TestStep",
    "label": "teststep",
    "query": "SHOW TAG VALUES ON vigie WITH KEY = \"teststep\""
   },
   { "name": "vigie_influxdb", "label": "InfluxDB", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Vigie x InfluxDB",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 8, "y": 0 },
   "content": "\n<center> <h1> Influx DB Dashboard (Alpha)  </h1> </center>\n"
  },
  { "title": "Vigie Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "TestSuite Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES EXACT CARDINALITY  ON \"vigie\" WITH KEY = \"testsuite\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestCase Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES EXACT CARDINALITY  ON \"vigie\" WITH KEY = \"testcase\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestStep Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES EXACT CARDINALITY  ON \"vigie\" WITH KEY = \"teststep\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestCases Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "TestCases" }
   ],
   "targets": [
    {
     "alias": "Testcases KO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"count_status\" FROM \"vigie\".\"dev\".\"vigie_testcase\" WHERE $timeFilter AND \"status\" = false GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Testcases OK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"count_status\" FROM \"vigie\".\"dev\".\"vigie_testcase\" WHERE $timeFilter AND \"status\" = true  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vigie TestSuite State",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT DISTINCT \"status\" FROM \"vigie\".\"dev\".\"vigie_testsuite\" WHERE \"testsuite\" =~ /^$TestSuite/  AND  $timeFilter GROUP BY \"testsuite\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestSuite Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestCase  Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"status\") AS \"last_status\" FROM \"vigie\".\"dev\".\"vigie_testcase\" GROUP BY \"testcase\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestSteps Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES EXACT CARDINALITY  ON \"vigie\" WITH KEY = \"teststep\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestSteps Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "TestSteps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"count_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE $timeFilter AND \"status\" = false  GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"count_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE $timeFilter AND \"status\" = true  GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vigie TestCase State",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"vigie\".\"dev\".\"vigie_testcase\" WHERE   \"testsuite\" =~ /^$TestSuite/  AND \"testcase\" =~ /^$TestCase/  AND $timeFilter GROUP BY * ORDER BY DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestSuites Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "TestSuites" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"count_status\" FROM \"vigie\".\"dev\".\"vigie_testsuite\" WHERE time > $timeFilter AND \"status\" = false GROUP BY \"testsuite\" FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Vigie Tests Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Vigie  State",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/ AND  $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Teststep Status (WIP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Status" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"status\") AS \"mean_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testsuite\" =~ /^$TestSuite/  AND  $timeFilter AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TestSuites",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "TestCase View : $TestSuite / $TestCase",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
     "repeat": "TestSuite",
     "yaxes": [
      { "format": "short", "label": "Status" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"status\") AS \"mean_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testsuite\" =~ /^$TestSuite/  AND  \"testcase\" =~ /^$TestCase/ AND  $timeFilter AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"status\") AS \"mean_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testsuite\" =~ /^$TestSuite/  AND  \"testcase\" =~ /^$TestCase/ AND  $timeFilter AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TestCase View : $TestSuite / $TestCase",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "Status" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"status\") AS \"mean_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testsuite\" =~ /^$TestSuite/  AND  \"testcase\" =~ /^$TestCase/ AND  $timeFilter AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"status\") AS \"mean_status\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testsuite\" =~ /^$TestSuite/  AND  \"testcase\" =~ /^$TestCase/ AND  $timeFilter AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TestSteps Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
     "repeat": "TestStep",
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 103 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 116 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 129 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 142 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Teststep State : $TestStep",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 155 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_teststep",
       "expr": "vigie_teststep_state{testsuite=~\"$TestSuite$\",testcase=~\"$TestCase$\",teststep=~\"$TestStep$\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{teststep}}",
       "query": "SELECT mean(\"status\") AS \"mean_responsetime\" FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/  AND $timeFilter GROUP BY time($__interval), \"teststep\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Vigie TestStep Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Vigie  TestStep Details",
   "type": "table-old",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"vigie\".\"dev\".\"vigie_teststep\" WHERE (\"status\" <> 1) AND  \"testcase\" =~ /^$TestCase/ AND \"testsuite\" =~ /^$TestSuite/  AND \"teststep\" =~ /^$TestStep/ AND  $timeFilter GROUP BY \"teststep\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}