{
 "title": "Vigie Go Runtime Lite",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Process Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "targets": [
    { "expr": "go_info" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "UP" }
   ]
  },
  {
   "title": "Vigie Go Runtime",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "content": "**Go runtime stats of vigie.demo.vigie.dev**\n\nThese statistics are presented transparently and for information only.\n\nThis lets you see the real resource need for Vigie.\n\nThis Vigie instance runs https://github.com/Vincoll/vigie-demo-test\n"
  },
  {
   "title": "Start at",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "process_start_time_seconds" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "Goroutines" }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "process Virtual memory (vsize)" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "process Resident memory (rss)" }
   ]
  },
  {
   "title": "Process memory",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "content": "**Process Memory**\n\n* `process_virtual_memory_bytes` – uses vsize – is all memory that the process can access, including memory that is swapped out, memory that is allocated, but not used, and memory that is from shared libraries.\n\n* `process_resident_memory_bytes` – multiplies rss – is number of memory pages the process has in real memory multiplied by pagesize. This excludes swapped out memory pages."
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds{}", "legendFormat": "Quantile: {{quantile}}" }
   ]
  },
  {
   "title": "System ressources used (/proc/PID/fd)",
   "type": "graph",
   "description": "process_open_fds – counts the number of files in /proc/PID/fd directory. This shows currently open regular files, sockets, pseudo terminals, etc.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds{}", "legendFormat": "Process open File Descriptors" }
   ]
  }
 ]
}