global:
  scrape_interval: 3s
  scrape_timeout: 2s
  evaluation_interval: 1m
scrape_configs:
  - job_name: Vigie
    scrape_interval: 1s
    scrape_timeout: 666ms
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - vigie:9000
