apiVersion: v1
kind: Service
metadata:
  name: vigie
spec:
  selector:
    app: vigie
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: tech
      port: 9000
      targetPort: 9000