apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigie-api
  labels:
    app: vigie
    service: vigie-api
    app.kubernetes.io/name: "vigie-api"
    app.kubernetes.io/part-of: "vigie"
    app.kubernetes.io/version: "null"
    app.kubernetes.io/component: "api"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vigie
      service: vigie-api
  template:
    metadata:
      labels:
        app: vigie
        service: vigie-api
    spec:
      restartPolicy: Always
      # CONTAINERS
      containers:
      - name: vigie
        imagePullPolicy: Always
        image: vincoll/vigie:null
        args:
        - run
        - --config
        - /app/config/vigie.toml

        # PROBES
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 3
          failureThreshold: 30
          timeoutSeconds: 1

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 1
        #   periodSeconds: 3
        #   failureThreshold: 30
        #   timeoutSeconds: 1
        

        # RESSOURCES
        resources:
          limits:
            cpu: 1500m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi

        # Mounts
        volumeMounts:
        - name: cm-vigie-config
          mountPath: /app/config/vigie.toml
          subPath: vigie.toml
          readOnly: true

      # Volumes
      volumes:
        - name: cm-vigie-config
          configMap:
            name: vigie-config