apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx  
    spec:
      restartPolicy: Always
      containers:
      - image: nginx:alpine
        name: nginx
        resources:
          limits:
            cpu: 60m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 20Mi


