apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always

      # CONTAINERS
      containers:
      - image: influxdb:1.7.7-alpine
        name: influxdb
        # CONTAINER ENV Var
        envFrom:
          - secretRef:
              name: sc-influx-env

        # RESSOURCES
        resources:
          requests:
            memory: "350Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "800m"
        # CONTAINER MOUNTS
        volumeMounts:
        - name: cm-influxdb-config
          mountPath: /etc/influxdb/influxdb.conf
          subPath: influxdb.conf
          readOnly: true
        - name: cm-influxdb-init
          mountPath: /docker-entrypoint-initdb.d/init-vigie.iql
          subPath: init-vigie.iql
          readOnly: true

      # VOLUMES
      volumes:
      - name: cm-influxdb-config
        configMap:
          name: cm-influxdb-config
      - name: cm-influxdb-init
        configMap:
          name: cm-influxdb-init
