apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb-http-tcp
      port: 8086
      targetPort: 8086
      protocol: TCP
    - name: influxdb-udp
      port: 8089
      targetPort: 8089
      protocol: UDP
  type: ClusterIP